build:
    environment:
        php:
            version: 7.1  
    dependencies:
        before:
            - pecl install ssh-beta           
filter:
    paths:
        - 'app/*'
    excluded_paths:
        - 'app/views/*'
        - 'app/config/*'
        - 'app/database/*'
checks:
    php: true
    javascript: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true